-- DollChecker V2 — daily missions, streaks and toy rotation.
--
-- A mission is one concrete play task for one child on one day, drawn from the
-- play ideas the analyzer already produced. Missions are generated by the app
-- (see `lib/features/missions/domain/mission_selection.dart`) and stored here so
-- the day's set is stable across devices and streaks can be counted.
--
-- Streaks are derived from the rows in this table rather than stored, so they
-- can never drift out of sync with the missions themselves.

create type mission_status as enum ('pending', 'completed', 'skipped');

create table public.daily_missions (
  id                uuid primary key default gen_random_uuid(),
  user_id           uuid not null references auth.users (id) on delete cascade,
  child_profile_id  uuid not null references public.child_profiles (id) on delete cascade,
  mission_date      date not null,
  -- Position within the day (0-based). Bounded so a bug cannot flood a day.
  slot              smallint not null check (slot between 0 and 4),
  -- The idea and toy a mission came from. Both are nullable: deleting a scan or
  -- a collection entry must not erase the history of what was completed, so the
  -- mission keeps its own copy of the text below.
  play_idea_id      uuid references public.play_ideas (id) on delete set null,
  toy_id            uuid references public.toys (id) on delete set null,
  title             text not null,
  description       text,
  skill             skill_key,
  duration_minutes  int,
  status            mission_status not null default 'pending',
  completed_at      timestamptz,
  created_at        timestamptz not null default now(),
  unique (child_profile_id, mission_date, slot)
);

create index daily_missions_child_date_idx
  on public.daily_missions (child_profile_id, mission_date desc);
create index daily_missions_user_status_idx
  on public.daily_missions (user_id, status);
-- Serves the streak query: completed dates for one child, newest first.
create index daily_missions_completed_idx
  on public.daily_missions (child_profile_id, mission_date desc)
  where status = 'completed';

alter table public.daily_missions enable row level security;

create policy "daily_missions_all_own" on public.daily_missions
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- Toy rotation
--
-- `last_played_at` is what rotation sorts on: a toy that was scanned months ago
-- but played yesterday is not due for rotation, and vice versa.
-- ---------------------------------------------------------------------------
alter table public.toys
  add column if not exists last_played_at timestamptz;

create index if not exists toys_last_played_idx
  on public.toys (user_id, last_played_at asc nulls first);

create or replace function public.touch_toy_last_played()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.status = 'completed'
     and new.toy_id is not null
     and (tg_op = 'INSERT' or old.status is distinct from 'completed')
  then
    update public.toys
       set last_played_at = coalesce(new.completed_at, now()),
           updated_at     = now()
     where id = new.toy_id;
  end if;
  return new;
end;
$$;

create trigger daily_missions_touch_toy
  after insert or update of status on public.daily_missions
  for each row execute function public.touch_toy_last_played();
